Add parameters dedicated to Dynaflow (#118)
powsybl/powsybl-dynawo pull request #119
Opened 2022-10-07 13:17 UTC by dimbdr

Signed-off-by: BAUDRIER Dimitri <dimitri.baudrier@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Linked to issue #118 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Add new specific parameters to the Dynaflow API

**What is the current behavior?** *(You can also link to an open issue here)*
Currently, the Dynaflow API gives only 4 specific parameters.

**What is the new behavior (if this is a feature change)?**
Adding 4 more parameters to the Dynaflow API, for a total of 8 specific parameters.
Some were described in the PowSyBl documentation but were not available in the API. Documentation will be updated according to the current modifications.

2022-10-10 11:54 UTC, sylvlecl requested changes
Thanks!
Implementation of loading from map still needs to be implemented :)

Note that we may implement at the same time that feature ? (but could be in another PR)
https://github.com/powsybl/powsybl-dynawo/issues/104#issuecomment-1262209738

2022-10-10 11:54 UTC, sylvlecl commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> -        Optional.ofNullable(properties.get(DSO_VOLTAGE_LEVEL)).ifPresent(prop -> parameters.setDsoVoltageLevel(Double.parseDouble(prop)));
We need to implement  the loading of new parameters here too.

Maybe code could be share with loading from the module ?

2022-10-10 11:54 UTC, sylvlecl commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> -        Optional.ofNullable(properties.get(DSO_VOLTAGE_LEVEL)).ifPresent(prop -> parameters.setDsoVoltageLevel(Double.parseDouble(prop)));
Note that we should also implement the method for update from a map, in DynaFlowProvider, not only the creation from a map.

2022-10-10 11:54 UTC, sylvlecl commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowParametersTest.java
> +        double timeStep = 2.6;
You are testing the same values as default values, so it's not really checking that those values are taken into account

2022-10-11 12:05 UTC, dimbdr commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowParametersTest.java
> +        double timeStep = 2.6;
Indeed, modification done

2022-10-11 15:30 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> -        Optional.ofNullable(properties.get(DSO_VOLTAGE_LEVEL)).ifPresent(prop -> parameters.setDsoVoltageLevel(Double.parseDouble(prop)));
> We need to implement the loading of new parameters here too.
> 
> Maybe code could be shared with loading from the module ?

I made a little change, by providing a new signature called `loading`.
The `load` method is not broken, and I can use the method `loading` with the new implemented method `updateSpecificParameters` in the DynaFlowProvider.
Though, I'm not quite sure about the way I implemented this `updateSpecificParameters`.

2022-10-12 10:01 UTC, sylvlecl approved these changes
Ok for me, thank you for the update!
I added very minor comments, nothing blocking though

2022-10-12 11:29 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> +    public void loading(Map<String, String> properties) {
Agreed, changed to `update`

2022-10-12 11:32 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> +                setChosenOutputs(Stream.of(prop.replace("[", "")
Thanks for the info, I wasn't sure about the format.
Modified, assumed there's no bracket in the string

2022-10-12 11:53 UTC, merged