Added GeneratorSynchronousFourWindingsProportionalRegulationsStepPm model
powsybl/powsybl-dynawo pull request #120
Opened 2022-10-11 09:44 UTC by dimbdr

Added GeneratorSynchronousFourWindingsProportionalRegulationsStepPm model

Added exportFileFromInMemoryFileSystemToHostFileSystem, in DynaWaltzTestUtil. Reason : helped exporting files from in-memory filesystem to host filesystem, while completing the test cases.

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Changes introduces another generator model used by DynaWaltz

**What is the current behavior?** *(You can also link to an open issue here)*
The DynaWaltz API of this project does not support the GeneratorSynchronousFourWindingsProportionalRegulationsStepPm model.

**What is the new behavior (if this is a feature change)?**
With these changes, the DynaWaltz API supports the GeneratorSynchronousFourWindingsProportionalRegulationsStepPm model

2022-10-18 14:33 UTC, gautierbureau approved these changes

2022-10-19 07:53 UTC, flo-dup requested changes

2022-10-19 08:56 UTC, dimbdr commented on dynawaltz/src/test/resources/com/powsybl/config/test/models.par
> +    <set id="GSFWPRSP">
I suppose, in a hypothetical future, we would want to change the values of the parameters in sort there is a specific set applied to a specific generator, to respect a certain type of test. I don't really know :smile: 

I added the new set because it felt coherent when reading what was written in `DynaWaltzTestUtil::setup`, however we could have used the same set for all the generators indeed.

2022-10-19 09:08 UTC, dimbdr commented on dynawaltz-dsl/src/test/java/com/powsybl/dynawaltz/dsl/DynaWaltzGroovyDynamicModelsSupplierTest.java
> +        boolean isGeneratorExtension = isThreeWindingsGeneratorExtension || isFourWindingsGeneratorExtension || isThreeWindingsGeneratorProportionalRegulationsExtension || isFourWindingsGeneratorProp
I change the signature of the method, I think it may be a bit more useful now.
Also, made the change on `isGeneratorExtension`

2022-10-19 09:09 UTC, dimbdr commented on dynawaltz/src/test/java/com/powsybl/dynawaltz/xml/DynaWaltzTestUtil.java
> +    protected void exportFileFromInMemoryFileSystemToHostFileSystem(Path pathFileInVirtualFileSystem, Path pathFileToRealFileSystem) {
Done, in a dedicated commit

2022-10-19 09:36 UTC, dimbdr commented
Sorry, another push 'cause of checkstyle not respected

2022-10-19 14:16 UTC, flo-dup approved these changes

2022-10-19 14:24 UTC, merged