Induced OmegaRef, unique instance
powsybl/powsybl-dynawo pull request #121
Opened 2022-10-20 08:16 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Issues #115 & #116 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

*Main thing* : OmegaRef can no longer be used in the dynamicModel DSL context.
OmegaRef accessibility is now managed by the DynaWaltzContext class. It will be used if there's a at least one Synchronous Generator declared in the dynamic model file, the one we provide via the DynaWaltz API. Otherwise, OmegaRef will be ignored when generating a dyd file.

Added the Generator Fictitious model, it's one of the generators type that does not need to be related to OmegaRef.

2022-10-26 12:34 UTC, flo-dup requested changes

2022-10-26 12:34 UTC, flo-dup commented on dynawaltz-dsl/src/test/resources/ieee14-currentlimitautomaton/dynawaltz-inputs/powsybl_dynawaltz.dyd
> +    <dyn:macroConnect connector="MC_DYNModelOmegaRef-GeneratorSynchronousFourWindingsProportionalRegulations" id1="OMEGA_REF" index1="0" id2="_GEN____2_SM"/>
the index should not always be 0, but should increment

2022-10-26 12:34 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    private final Map<BlackBoxModel, Integer> libIndexMap = new HashMap<>();
I think we should be able to remove this two fields

2022-10-26 12:34 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +        int index = context.getLibIndex(this);
this was working before because there was several instances of OmegaRef, but now you can find the index of the connected black box easily as everything is centralized here.

2022-10-31 09:29 UTC, dimbdr commented on dynawaltz-dsl/src/test/java/com/powsybl/dynawaltz/dsl/DynaWaltzGroovyEventModelsSupplierTest.java
> -        int expectedEventModelsSize =  numLines;
Done

2022-10-31 10:22 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/GeneratorFictitious.java
> +public class GeneratorFictitious extends AbstractGeneratorModel {
The `GeneratorFictitious` exists in the Dynawo models collection indeed.
https://github.com/dynawo/dynawo/blob/master/dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/GeneratorFictitious.mo

**The reason I introduced this generator in the current modifications**

I introduced at first this new model, to understand how to not connect OmegaRef.
By its definition, OmegaRef is not affiliated to generators that are not synchronous.
The `GeneratorFictitious` is one the few generators that are not synchronous. It is also is a simpler model compared to the others generator models.
Then, a few problems occured while implementing the `GeneratorFictitious`,  that led me to make some modifications about the way OmegaRef is used, taking into account the issues #115 and #116
The changes have been made about OmegaRef, and the `GeneratorFictitious` was ready to be used.

Despite these, one case was still unresolved : what if we declare one or multiple generators, and none of them are synchronous?
In this case, OmegaRef has not to be exported in the dyd file.
Based on the `GeneratorFictitious`, I could write a test case to verify if OmegaRef would be ignored in such situation.

2022-10-31 10:54 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/GeneratorModel.java
> -    String getOmegaRefPuVarName();
I agree, though I'd prefer to let this change as is, for now.
Currently there's no model of a non-synchronous generator using the OmegaRef.
Sure we could make the right modification while introducing a new non-synchronous model using OmegaRef?

2022-10-31 13:40 UTC, dimbdr commented on dynawaltz-dsl/src/test/resources/ieee14-currentlimitautomaton/dynawaltz-inputs/powsybl_dynawaltz.dyd
> +    <dyn:macroConnect connector="MC_DYNModelOmegaRef-GeneratorSynchronousFourWindingsProportionalRegulations" id1="OMEGA_REF" index1="0" id2="_GEN____2_SM"/>
Ups, that's right!
Corrected

2022-10-31 13:41 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    private final Map<BlackBoxModel, Integer> libIndexMap = new HashMap<>();
Removed

2022-10-31 13:42 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +        int index = context.getLibIndex(this);
`getLibIndex` removed, and replaced here by an index search of the connected BlackBox into the modelConnections list handed by the DynaWaltzContext

2022-10-31 13:43 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +    public OmegaRef(List<DynamicModel> dynamicModels) {
Modified the constructor signature

2022-10-31 14:03 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +    private final List<GeneratorSynchronousModel> generatorDynamicModelsAssociated;
Renamed

2022-10-31 14:34 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +                    if (Objects.nonNull(generator)) {
Modified

2022-10-31 14:36 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +                        LOG.warn("Generator {} not found in DynaWaltz context. Id : {}", generatorModel.getLib(), generatorModel.getDynamicModelId());
'cause of the lambda, since it doesn't manage the exceptions.
I replaced the log by an exception by the way, in order to approach a bit more the original behaviour of the `getModelsConnectedTo` method

2022-10-31 14:36 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +                .forEach(generatorModel -> {
`for` loop used

2022-10-31 14:43 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +    public boolean hasToBeExported() {
I agree.
I deleted the `hasToBeExported` method, and wrote a `getSynchronousGenerators` method.
The result will be interpreted by whoever calls it.

2022-10-31 15:00 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/AbstractDynamicBlackBoxModel.java
> +public abstract class AbstractDynamicBlackBoxModel extends AbstractBlackBoxModel implements DynamicModel {
Removed

2022-10-31 15:05 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +        for (BlackBoxModel blackBoxModel : generatorDynamicModelsAssociated.stream().map(BlackBoxModel.class::cast).collect(Collectors.toList())) {
Modified, `GeneratorModel` intherits from `BlackBoxModel`

2022-11-14 10:47 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +                Pair.of("index1", Integer.toString(context.getModelsConnections().get(this).indexOf(connected)))
Tried to bring a solution with https://github.com/powsybl/powsybl-dynawo/pull/121/commits/85427db3b3bb5110bdef3eb28b0b2d8557384be3

2022-11-16 14:32 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/GeneratorFictitious.java
> +public class GeneratorFictitious extends AbstractGeneratorModel {
Ok! I just didn't know `GeneratorFictitious` was a real model. No need to detail that any further! :slightly_smiling_face:

2022-11-16 15:11 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/GeneratorFictitious.java
> +package com.powsybl.dynawaltz.dynamicmodels;
You should add a (c) 2022 license header and put yourself as an author on the new files

2022-11-16 15:11 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/GeneratorModel.java
> -    String getOmegaRefPuVarName();
That would have been better to introduce it right away, but let's move on, this PR is getting too old :older_man:

2022-11-16 16:28 UTC, flo-dup requested changes

2022-11-16 16:28 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +            Pair<GeneratorSynchronousModel, BusModel> currentPair = lGenByBus.get(index1);
two things, first you shouldn't have to do something like that, you could use a `Map<BlackBoxModel, Integer>` for instance. And then there's nothing which strongly ensures you that `lGenByBus` is already filled up - even though it is ok currently. What we could do is create a `Map<BlackBoxModel, Integer> getConnectedModelsIndices()` method which computes the map if null. It will be called in both `getModelsConnectedTo` and `writeMacroConnect`.

2022-11-16 16:28 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    public Stream<BlackBoxModel> getUserBlackBoxModelStream() {
Maybe `getInputBlackBoxModelStream`? But you can put this private in fact and add a comment saying that it does not include the implicit OmegaRef dynamicModel.

2022-11-16 16:35 UTC, flo-dup commented on dynawaltz/src/test/resources/dyd.xml
> +    <dyn:macroConnect connector="MC_DYNModelOmegaRef-NetworkBus" id1="OMEGA_REF" index1="5" id2="NETWORK" name2="NHV1"/>
@gautierbureau what if there are two synchronous generators on the same bus, should there be two `macroConnect`, or only one, and if only one, does the retained index matter?

2022-11-17 10:20 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +            Pair<GeneratorSynchronousModel, BusModel> currentPair = lGenByBus.get(index1);
I agree, there's no guarantee that the `lGenByBus` has been filled up if `getModelsConnectedTo` is not called beforehand, it's its weakness.
But, in the `writeMacroConnect`, I have quite a hard time to figure out how to attribute the right index to the `connected` object, if the `lGenByBus` is empty. In my opinion, it might be the same problem with a `Map<BlackBoxModel, Integer>` when it's empty.
For now, the only way I see to make it right with your proposal of `Map<BlackBoxModel, Integer> getConnectedModelsIndices()`, is to recycle the big part in `getModelsConnectedTo` that finds the couple Generator-Bus in the network detained by the context.
I'll try it, but if someone has a better idea, I'd be glad :smile:

2022-11-17 10:21 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/GeneratorFictitious.java
> +package com.powsybl.dynawaltz.dynamicmodels;
Done

2022-11-17 10:21 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +        // New way to handle the OmegaRef : there's only one instance.
Deleted

2022-11-17 10:23 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +        for (BlackBoxModel generatorModel : synchronousGenerators.stream().map(BlackBoxModel.class::cast).collect(Collectors.toList())) {
for loop simplified

2022-11-17 10:23 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +        List<BlackBoxModel> lGenAndBuses = new ArrayList<>();
Modified the name of the attribute

2022-11-17 10:33 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    public Stream<BlackBoxModel> getUserBlackBoxModelStream() {
Done

2022-11-18 15:09 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/OmegaRef.java
> +            Pair<GeneratorSynchronousModel, BusModel> currentPair = lGenByBus.get(index1);
nice!

2022-11-18 15:09 UTC, flo-dup approved these changes

2022-11-18 15:23 UTC, merged