Upd dynaflow parameters
powsybl/powsybl-dynawo pull request #123
Opened 2022-10-24 12:46 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
The Dynaflow Launcher team has requested to not export Dynaflow parameters if they're not set by a user or the configuration platform.
By default, there's no exported parameter.

**What is the current behavior?** *(You can also link to an open issue here)*
All the Dynaflow parameters have a default value, and are all exported when serialized in JSON format.

**What is the new behavior (if this is a feature change)?**
If a parameter is set by the user or by the platform configuration, then this parameter wiill be exported to a serialized JSON format.
Otherwise, it will be ignored.

**Other information**:
In addition, a commit that deletes 2 parameters, as requested : VscAdGenerators and LccAsLoads

2022-10-25 11:27 UTC, marcochiaramello requested changes

2022-10-25 11:27 UTC, marcochiaramello commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowParametersTest.java
> +        //assert timeOfEvent == dynaFlowParameters.getTimeOfEvent();
could you remove this commented line? thx

2022-10-25 11:38 UTC, dimbdr commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowParametersTest.java
> +        //assert timeOfEvent == dynaFlowParameters.getTimeOfEvent();
Ups
Done

2022-10-25 11:50 UTC, marcochiaramello approved these changes

2022-11-14 10:11 UTC, dimbdr commented on dynaflow/src/test/java/com/powsybl/dynaflow/json/JsonDynaFlowParametersSerializerTest.java
> +        assert expectedStartTime == dynaFlowParameters.getStartTime();
Corrected

2022-11-16 12:03 UTC, gautierbureau approved these changes

2022-11-16 13:50 UTC, flo-dup requested changes
Could you remove the `Objects.nonNull` and `Objects.isNull`?

2022-11-16 14:18 UTC, flo-dup commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> +    private static final String PRECISION = "precision";
You have a clash between `PRECISION` static variable and `precision` variable. Could you rename one of them?

2022-11-16 14:32 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowParameters.java
> +    private static final String PRECISION = "precision";
Done

2022-11-16 15:04 UTC, flo-dup approved these changes

2022-11-16 15:05 UTC, merged