DynaFlow : Add startingPointMode parameter
powsybl/powsybl-dynawo pull request #128
Opened 2022-11-16 15:36 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#125 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Add the StartingPointMode parameter to the DynaFlow API (and it must be serialized in lower case).

2022-11-16 16:08 UTC, marcochiaramello requested changes

2022-11-16 16:32 UTC, dimbdr commented on dynaflow/src/test/resources/dynaflow_parameters_set_serialization.json
> +      "startingPointMode" : "warm",
It's true about the JSON configuration sent to DynaFlow.
However, this JSON file purpose is to import a configuration in the DynaFlow API in the PowSyBl context.

2022-11-16 16:57 UTC, flo-dup requested changes

2022-11-16 16:57 UTC, flo-dup commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +        FLAT("flat");
Could you use once flat in the tests? it's used nowhere so fat.

2022-11-16 16:57 UTC, flo-dup commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +            return name;
you could use `name().toLowerCase();` instead so that you don't have a redundant parameter.

2022-11-17 09:59 UTC, marcochiaramello commented on dynaflow/src/test/resources/dynaflow_parameters_set_serialization.json
> +      "startingPointMode" : "warm",
ok, thanks!

2022-11-17 10:02 UTC, rosiereflo approved these changes

2022-11-17 13:27 UTC, merged