Dynaflow refactor
powsybl/powsybl-dynawo pull request #130
Opened 2022-11-18 10:16 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Mainly changing the IIDM version.

2022-11-18 13:01 UTC, marcochiaramello approved these changes

2022-11-24 08:04 UTC, gautierbureau approved these changes

2022-11-24 13:00 UTC, flo-dup requested changes

2022-11-24 13:00 UTC, flo-dup commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConfig.java
> +        return null;
You can use `Optional::map` here to have something more compact:
```suggestion
        return platformConfig.getOptionalModuleConfig("dynaflow")
                .map(config -> new DynaFlowConfig(config.getPathProperty("homeDir"), config.getBooleanProperty("debug", DEFAULT_DEBUG)))
                .orElse(null);
```

2022-11-24 13:00 UTC, flo-dup commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowProvider.java
> +        return VERSION;
`VERSION` is equal to 0.1, shouldn't it be 1.3.1? It's compared to the result of `dynaflow-launcher --version` at least.

2022-11-24 13:31 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowProvider.java
> +        return VERSION;
I wasn't sure. Now that you pointed it out and I made the change, it seems obvious :laughing:

2022-11-24 16:38 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +    public static final String VERSION = "1.3.1";
@flo-dup and I are raising a question about the version.

Each time DynaFlowLauncher has a new release, we increment this attribute according to the new version.
However, if a new DynaFlowLauncher version doesn't imply to make some breaking change in the DynaFlow API, would it be interesting to have the possibility to call an older version?

2022-11-25 12:46 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +    public static final String VERSION = "1.3.1";
After talking to @marcochiaramello and @rosiereflo, to sum up:

- set a default version, that will follow the release version of DynaFlow Launcher
- set a minimum version, which serves as a lower bound in the range of compatible versions of DynaFlow Launcher. This minimum version might change in the future if there are breaking changes in the API.
- add a version parameter, that allows a user to set the DynaFlow version. Need to make a verification that the version interval is respected.

2022-11-25 15:57 UTC, flo-dup requested changes

2022-11-25 15:57 UTC, flo-dup commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +        assertEquals(IidmXmlVersion.V_1_4.toString("."), IIDM_VERSION);
I think you can remove that test which is not that useful, plus it produces a code smell.

2022-11-25 15:57 UTC, flo-dup commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +        public static DynaFlowVersion of(String version) {
You could also return an `Optional<DynaFlowVersion>` in both `DynaFlowVersion::of`, it would make the code a bit clearer when checking the version don't you think? with a `.map(v -> v.compareTo(version) >= 0).orElse(false)` instead of catching an exception

2022-11-25 16:29 UTC, dimbdr commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +        assertEquals(IidmXmlVersion.V_1_4.toString("."), IIDM_VERSION);
removed

2022-11-25 16:29 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +        public static DynaFlowVersion of(String version) {
Oh nice, it's quite better indeed!
Done!

2022-11-25 16:35 UTC, dimbdr commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowConstants.java
> +    public static final String VERSION = "1.3.1";
For the last bullet point, it's not as trivial as it seems with the last commits.
We'll make another PR to include this DynaFlow version parameter.

2022-11-25 16:41 UTC, flo-dup approved these changes

2022-11-25 16:48 UTC, merged