Add merge/unmerge loads feature.
powsybl/powsybl-dynawo pull request #131
Opened 2022-11-18 13:18 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
fixes #122 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Proposal on how to merge/unmerge bunch of loads on a same bus in a network.

TODO: is it always used, or is it a an option (e.g, activate/deactivate in the configuration of DynaFlow/DynaWaltz) ?
When answered, need to use the DynawoResultsMergeLoads in both DynaWatlzProvider and DynaflowProvider.

2022-11-24 15:39 UTC, dimbdr commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +    public void testUpdateWithMergeLoads() throws Exception {
I'm wondering.
I created this test, but is it really necessary to compare the network unmerged with the resource `SmallBusBranch_outputIIDM.xml`?
Since there are tests associated to the methods merge/unmerge (DynawoResultsMergeLoadsTest), and there are supposed to guarantee it works, then it should not be necessary to reconfirm the unmerge is successful when reading the network transformed into a xiidm file. I might be wrong.

2022-11-28 10:36 UTC, geofjamg requested changes

2022-11-28 10:36 UTC, geofjamg commented on commons/src/main/java/com/powsybl/dynawo/commons/DynawoResultsMergeLoads.java
> +    public DynawoResultsMergeLoads(String idNetwork) {
You should directly pass the Network it self to avoid consistency check in merge methods

2022-11-28 10:36 UTC, geofjamg commented on commons/src/main/java/com/powsybl/dynawo/commons/DynawoResultsMergeLoads.java
> +public class DynawoResultsMergeLoads {
A very general design comment: you chose to to remove/add loads in the initial network, there is many drawbacks to this and for me it breaks the DynamicSimulation and LoadFlow API contract. When an IIDM network is passed to the run method we are not supposed to change anything except state variables values at the end.
Especially with the network store IIDM implementation (the one used in GridSuite), this will have serious performance impacts as a load that is removed and re-created will be resync to the DB.

Also in you actual implementation, we loose all load extensions, so the merge/unmerge operation is not idempotent. More generally which such a strategi is very difficult to ensure that network will be exactly the same at the end of the run.

The only alternative I can see is to clone the network, merge loads on the clone and then update initial network from the clone updated at the end of the simulation. The drawback is probably the performance. Network cloning (using NetworkXml.copy) could be 2 or 3 s on large network. 
A long term solution could be to support network variant on structure modification (like we already support in IIDM impl of network store), but there would a lot of work to have it working in core IIDM impl.

To test: what is the performance gain of load merging (cloning time vs simulation time decrease). Maybe it worth it only in security analysis and not on simple loadflow ?

2022-11-28 14:44 UTC, dimbdr commented on commons/src/main/java/com/powsybl/dynawo/commons/DynawoResultsMergeLoads.java
> +    public DynawoResultsMergeLoads(String idNetwork) {
Done

2022-11-28 16:06 UTC, dimbdr commented on commons/src/main/java/com/powsybl/dynawo/commons/DynawoResultsMergeLoads.java
> +public class DynawoResultsMergeLoads {
Thanks for your comment !

I wasn't sure if it was allowed to modify the loads in a current network. Following your explanation, I agree it is quite a concern. 
Changed the way to handle the network alteration: a DynawoResultsMergeLoads duplicates the aimed network, and do the modifications on the copied network.

As for performance gain/loss, I may not be suited to answer with accuracy.
Someone from the Dynawo team would like to test this?

2023-02-17 09:31 UTC, flo-dup approved these changes

2023-02-17 09:43 UTC, merged