Generator pq
powsybl/powsybl-dynawo pull request #138
Opened 2022-11-29 15:22 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Introduce the PQ generator

2022-11-30 14:27 UTC, flo-dup requested changes

2022-11-30 14:27 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +    default String getOmegaRefPuVarName() {
We try to use default keyword only for retrocompatibility: if an interface evolves with a new method we can give a default implementation so that users don't need to add anything in their old implementation. Here that's not the problem, so that means that you need to add a, wait for it, `AbstractGeneratorConnectedToOmegaRefModel` class :face_exhaling:

2022-11-30 14:27 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +public interface GeneratorConnectedToOmegaRefModel extends GeneratorModel {
isn't there a more specific word for these kind of generators?

2022-11-30 14:27 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +package com.powsybl.dynawaltz.dynamicmodels.staticref.generators.omegaref;
You can add license header and authorship. To ease up the license scanning done by the linux foundation, we've been recently asked to add a "SPDX identifier":

```
/**
 * Copyright (c) 2022, RTE (http://www.rte-france.com/)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * SPDX-License-Identifier: MPL-2.0
 */
```

2022-11-30 14:27 UTC, flo-dup commented on dynawaltz-dsl/src/main/groovy/com/powsybl/dynawaltz/dsl/dynamicmodels/GeneratorPQGroovyExtension.groovy
> + * Copyright (c) 2020, RTE (http://www.rte-france.com)
Could you fix the header (2022 + SPDX identifier) and add authorship?

2022-11-30 14:45 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +public interface GeneratorConnectedToOmegaRefModel extends GeneratorModel {
`AsynchronousGeneratorModel`?

2022-11-30 16:13 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +    default String getOmegaRefPuVarName() {
Ah damn, I thought I could avoid this abstract.
It's quite an issue. For each synchronous generator, we would have 6 inheritance levels. Sonar is not really happy about it.
I don't have any idea right now how to fix this.

2022-11-30 16:49 UTC, geofjamg commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +    default String getOmegaRefPuVarName() {
Sonar issues are not alway relevant. In many places in powsybl, we do not follow this 6 levels recommandation.
For some complex data model, it could be ok to be greater than 6

2022-12-01 10:57 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +public interface GeneratorConnectedToOmegaRefModel extends GeneratorModel {
I don't have the full picture.
@gautierbureau and I talked a bit about the names, still it's not really clear how to name correctly all those objects.

tl;dr : we'll not use `AsynchronousGeneratorModel`, sorry :cry: 


**Long answer, it's how I understand it:**
After we discussed, the name `SynchronousGenerator` is more about a state than a definition. A synchronous generator might be non-synchronous at some point in time.
But we do not concern ourselves too much about this situation, in the initial state of the model context, yet.

However, all the other generators that are not explicitly described as synchronous in the powsybl-dynawo model, are not necessarily non-synchronous, nor asynchronous.
I suppose these generators may be synchronous at a certain point in time, or it's a question about how simpler/complex we want to describe a network.
I don't have all the details though, I'm not well versed into the subject.
Someone from the Dynawo team would be able to elaborate more accurately about these notions.

Nonetheless, it might not be helpful to oppose synchronous/asynchronous generators. We would misinterpret the meaning of those objects, for what I understand.

2022-12-01 12:24 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +    default String getOmegaRefPuVarName() {
Thanks for the info, I created the `AbstractGeneratorConnectedToOmegaRefModel`

2022-12-01 12:29 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/dynamicmodels/staticref/generators/omegaref/GeneratorConnectedToOmegaRefModel.java
> +package com.powsybl.dynawaltz.dynamicmodels.staticref.generators.omegaref;
Oops, forgot again...
Done

2022-12-01 12:29 UTC, dimbdr commented on dynawaltz-dsl/src/main/groovy/com/powsybl/dynawaltz/dsl/dynamicmodels/GeneratorPQGroovyExtension.groovy
> + * Copyright (c) 2020, RTE (http://www.rte-france.com)
Done

2023-01-04 17:14 UTC, flo-dup approved these changes
Just still not that happy with the `GeneratorConnectedToOmegaRefModel` name :disappointed:

2023-01-04 17:14 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/generators/AbstractGeneratorConnectedToOmegaRefModel.java
> +public abstract class AbstractGeneratorConnectedToOmegaRefModel extends AbstractGeneratorModel implements GeneratorConnectedToOmegaRefModel {
wondering if we really need this class...
- If `GeneratorPQ` is the only generator of that type, that's only to avoid duplicating `generator_omegaRefPu`
- If there could be more, ok but then we should do the same as in PR #146: the class should not be abstract and should have the lib name as constructor parameter

2023-01-06 10:21 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/generators/AbstractGeneratorConnectedToOmegaRefModel.java
> +public abstract class AbstractGeneratorConnectedToOmegaRefModel extends AbstractGeneratorModel implements GeneratorConnectedToOmegaRefModel {
Made the modification with the latest commits.
GeneratorConnectedToOmegaRefModel is no longer abstract, and there is additionnal info into the config file in the DSL part, that is dedicated to this object. Similar to what's done in #146

2023-03-10 16:01 UTC, merged