Add bus model
powsybl/powsybl-dynawo pull request #144
Opened 2022-12-14 12:35 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Add bus model

2022-12-14 15:23 UTC, flo-dup requested changes

2022-12-14 15:23 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    private final Map<Couple<Model>, MacroConnector> connectorsMap = new LinkedHashMap<>();
After some digging, I think there's some unneeded complexity introduced here, we should be able to deal with `Couple<String>` instead, that is with the names. Indeed, this is only needed not to have the model1, model2 connect twice (once as model1-model2, once as model2-model1). To do this, instead of the `usedMacroConnectors` in `DydXml::writeDynamicModels`, we can create a `Set<Couple<Model>>` to be sure to have only once the connect.

2022-12-14 15:23 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/xml/DydXml.java
> +            List<MacroConnector> usedMacroConnectors = new ArrayList<>();
Instead of this, I think you could loop over the couples after creating the set of all couples:
``` 
Set<Couple<Model>> allModelCouples = context.getModelsConnections().entrySet().stream()
                .flatMap(e -> e.getValue().stream().map(m -> new Couple<>(e.getKey(), m)))
                .collect(Collectors.toCollection(LinkedHashSet::new));
```

2022-12-15 12:50 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +        return connectorsMap.get(new Couple<Model>(bbm, model));
Corrected

2022-12-15 12:50 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +            var key = new Couple<Model>(bbm, connectedBbm);
Corrected

2022-12-15 12:50 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/utils/Couple.java
> +            Couple<T> cpl = (Couple) obj;
Corrected

2022-12-15 13:26 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +        if (connected instanceof GeneratorModel) {
Added comment, though I'm not sure it helps to understand the trick

2022-12-15 14:26 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +            int index = getConnectedModelsIndices(context).get(connected);
Haha! I fell into a trap.
getConnecteModelsIndices is also called in OmegaRef::getModelsConnectedTo.
If we remove the buses, then there's no longer any macroconnector that associate the OmegaRef with the buses.

2022-12-15 15:28 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    private final Map<Couple<Model>, MacroConnector> connectorsMap = new LinkedHashMap<>();
Modified connectorsMap

2022-12-15 15:28 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/xml/DydXml.java
> +            List<MacroConnector> usedMacroConnectors = new ArrayList<>();
Nice, implemented

2022-12-15 15:58 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +            }
Done

2022-12-19 16:02 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +            int index = getConnectedModelsIndices(context).get(connected);
I did remove them, then we need to do it in two steps

2022-12-19 16:34 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +        if (connected instanceof GeneratorModel) {
Fixed the trick so I removed the comment

2022-12-22 14:08 UTC, flo-dup approved these changes

2022-12-22 14:16 UTC, merged