Line2
powsybl/powsybl-dynawo pull request #147
Opened 2022-12-23 15:52 UTC by dimbdr

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Introduce Line model

2023-01-04 11:02 UTC, flo-dup requested changes
Similarly to the bus model, could you also add a LineGroovyExtension in dynawaltz-dsl

2023-01-04 11:08 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/automatons/CurrentLimitAutomaton.java
> +        BlackBoxModel connectedBbm = context.getStaticIdBlackBoxModelMap().get(line.getId());
:disappointed: well spotted!

2023-01-05 12:47 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/lines/StandardLine.java
> +        return Collections.emptyList();
Honestly I don't know.
I made this development according to this example : https://github.com/dynawo/dynawo/blob/master/nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.dyd

I didn't find any dyd file that describes a line with macroconnectors. So for now, I just assumed there's no varsMapping.

2023-01-05 13:14 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/lines/StandardLine.java
> +        writer.writeStartElement(DYN_URI, "blackBoxModel");
Indeed, but I might be wrong on this.

2023-01-05 14:18 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/lines/StandardLine.java
> +        this.id = "line" + atomicInteger.incrementAndGet();
Well, it's useless. I removed this id in https://github.com/powsybl/powsybl-dynawo/pull/147/commits/419f42f92defeeaa7be7e1303592ecc1ff4b5b50

2023-01-05 14:19 UTC, dimbdr commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/automatons/CurrentLimitAutomaton.java
> +    public String getMonitored() {
Done in https://github.com/powsybl/powsybl-dynawo/pull/147/commits/f11e90fee4e0be909b1bb6c7b989366639213639

2023-01-05 15:24 UTC, dimbdr commented on dynawaltz-dsl/src/main/groovy/com/powsybl/dynawaltz/dsl/models/lines/LineGroovyExtension.groovy
> + * An implementation of {@link DynamicModelGroovyExtension} that adds the <pre>Bus</pre> keyword to the DSL
Oops, it adds the `Line` word, not `Bus`

2023-01-05 15:53 UTC, dimbdr commented on dynawaltz-dsl/src/main/groovy/com/powsybl/dynawaltz/dsl/models/lines/LineGroovyExtension.groovy
> + * An implementation of {@link DynamicModelGroovyExtension} that adds the <pre>Bus</pre> keyword to the DSL
Fixed

2023-02-02 15:51 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/lines/StandardLine.java
> +        return Collections.emptyList();
Indeed, none so far

2023-02-03 17:03 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/lines/StandardLine.java
> +        writer.writeStartElement(DYN_URI, "blackBoxModel");
Better reuse the write of `AbstractBlackBoxModel`

2023-02-03 17:10 UTC, flo-dup approved these changes

2023-02-03 17:12 UTC, merged