Refactor dynamic model connection
powsybl/powsybl-dynawo pull request #181
Opened 2023-02-23 10:12 UTC by Lisrte

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Refactor

**What is the new behavior (if this is a feature change)?**
DynaWaltzContext returns directly the dynamicModel linked to the static id or a default model/exception if not found depending on the method called

2023-02-23 14:35 UTC, flo-dup requested changes

2023-02-23 14:35 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +        return (BusModel) context.getDynamicModelOrDefaultBus(generator.getTerminal());
you might get a `ClassCastException` here. Shouldn't `getDynamicModelOrDefaultBus` return a `BusModel`?

2023-02-23 14:35 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/buses/StandardBus.java
> +        return bus.getGeneratorStream().map(g -> context.getDynamicModelOrThrows(g.getId())).collect(Collectors.toList());
Not the purpose of this PR, but there's been quite a failure here! buses might connect to many other models which are not generators.

2023-02-24 09:21 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/OmegaRef.java
> +        return (BusModel) context.getDynamicModelOrDefaultBus(generator.getTerminal());
`getDynamicModelOrDefaultBus` now returns a `BusModel` (same for `getDynamicModelOrDefaultBus` with `LineModel`)

2023-02-24 09:21 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/buses/StandardBus.java
> +        return bus.getGeneratorStream().map(g -> context.getDynamicModelOrThrows(g.getId())).collect(Collectors.toList());
Should I open a PR for that ?

2023-02-24 12:25 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/buses/StandardBus.java
> +        return bus.getGeneratorStream().map(g -> context.getDynamicModelOrThrows(g.getId())).collect(Collectors.toList());
No, so far we mainly work with the default bus, so we'll handle this later. But could you just write an issue so that we don't forget this?

2023-02-24 12:30 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +        throw new PowsyblException("The model identified by the static id " + staticId + " is not a line model");
Could you add a very basic unit test so that these lines are covered?

2023-02-27 09:58 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/buses/StandardBus.java
> +        return bus.getGeneratorStream().map(g -> context.getDynamicModelOrThrows(g.getId())).collect(Collectors.toList());
Outlined in Issue #183

2023-02-27 10:35 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +        throw new PowsyblException("The model identified by the static id " + staticId + " is not a line model");
DynamicModelsXmlTest::testDynamicModelGetterException added

2023-02-27 15:45 UTC, flo-dup requested changes

2023-02-27 15:47 UTC, flo-dup commented on dynawaltz/src/test/java/com/powsybl/dynawaltz/xml/DynamicModelsXmlTest.java
> +    public void testDynamicModelGetterException() {
You should remove the public identifier now that we've switched to Junit5

2023-02-28 09:22 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +    public BusModel getDynamicModelOrDefaultBus(Terminal terminal) {
I agree using a iidm object as parameter is a little odd.
I removed `getConnectableBusModel(Terminal)` and replaced it with BusUtils::getConnectableBusStaticId called by the dynamic models.

2023-02-28 09:28 UTC, Lisrte commented on dynawaltz/src/test/java/com/powsybl/dynawaltz/xml/DynamicModelsXmlTest.java
> +    public void testDynamicModelGetterException() {
Fixed

2023-03-08 16:13 UTC, merged