Refactor disconnection events
powsybl/powsybl-dynawo pull request #197
Opened 2023-04-05 11:49 UTC by Lisrte

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Refactor

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**
In DSL, replace EventSetPointBoolean and EventQuadripoleDisconnection with a common tag Disconnect
Add the possibility to disconnect transformer and load

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-04-05 11:58 UTC, gautierbureau commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/generators/DefaultGeneratorModel.java
> +    public String getTerminalVarName() {
For a default generator this does not exist

2023-04-20 09:14 UTC, flo-dup requested changes

2023-04-20 12:18 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/events/EventQuadripoleDisconnection.java
> +    public EventQuadripoleDisconnection(Line equipment, double startTime, boolean disconnectOrigin, boolean disconnectExtremity) {
We can disconnect origin, extremity or both, the use of ` Branch<?> ` does not match our need

2023-04-21 14:08 UTC, flo-dup approved these changes

2023-04-21 14:14 UTC, merged