Add tap changer automatons
powsybl/powsybl-dynawo pull request #198
Opened 2023-04-13 08:41 UTC by Lisrte

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**
Add the following models :
- LoadTwoTransformers
- LoadOneTransformerTapChanger
- LoadTwoTransformersTapChangers
- TapChangerAutomaton
- TapChangerBlockingAutomaton

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

2023-04-25 12:55 UTC, flo-dup requested changes

2023-04-26 13:20 UTC, Lisrte commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/DynaWaltzContext.java
> +                .filter(dm -> staticId.equalsIgnoreCase(dm.getDynamicModelId()))
Use of _equals_ instead

2023-04-26 13:22 UTC, Lisrte commented on dynawaltz-dsl/src/main/groovy/com/powsybl/dynawaltz/dsl/automatons/TapChangerBlockingAutomatonGroovyExtension.groovy
> +        void UMeasurement(List<String> staticIds) {
The method name has to match the one used in the groovy script

2023-04-26 13:25 UTC, Lisrte commented on dynawaltz-dsl/src/main/groovy/com/powsybl/dynawaltz/dsl/automatons/TapChangerBlockingAutomatonGroovyExtension.groovy
> +        void transformers(String[] staticIds) {
`UMeasurement(String staticId)` is useless, refactor `UMeasurement` methods to match `transformers` processing

2023-05-04 12:26 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/loads/LoadTwoTransformers.java
> +            new VarMapping("transformerT_P1Pu_value", "p"),
should we call `TransformerSide::getSideSuffix` when there is `T` or `D` in the the variable names? Or call something like `LoadTwoTransformers.getTransformerVarName(side)`?

2023-05-04 12:27 UTC, flo-dup commented on dynawaltz/src/main/java/com/powsybl/dynawaltz/models/transformers/TapChangerModel.java
> +    String TAP_CHANGER_BLOCKING_BLOCKED_T = "tapChangerBlocking_blockedT";
Same kind of remark, we could use `TransformerSide::getSideSuffix`

2023-05-05 13:16 UTC, flo-dup approved these changes

2023-05-05 13:26 UTC, merged