Add readthedocs
powsybl/powsybl-dynawo pull request #356
Opened 2024-05-28 14:06 UTC by Lisrte

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

Documentation

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**
Add readthedocs folder
Transfer powsybl-dynawo documentation from website to readthedocs
Add "build-docs" directory to the .gitignore file. 

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**Other information**:

2024-05-31 14:47 UTC, flo-dup requested changes

2024-06-25 09:42 UTC, olperr1 submitted a review, later dismissed

2024-06-25 09:42 UTC, olperr1 commented on docs/conf.py
> +html_css_files = ['styles/styles.css']
This file is missing. Could you use the one which was added to `powsybl-core`?

2024-06-26 11:36 UTC, flo-dup approved these changes

2024-06-26 11:46 UTC, merged