Add simulation criteria parameter
powsybl/powsybl-dynawo pull request #377
Opened 2024-09-10 13:01 UTC by Lisrte

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes #309 

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

2024-09-11 15:50 UTC, flo-dup requested changes

2024-09-11 15:50 UTC, flo-dup commented on dynawo-simulation/src/main/java/com/powsybl/dynawo/DynawoSimulationParameters.java
> +    public boolean hasCriteriaFile() {
you could use `Optional<Path>` as return type for `getCriteriaFilePath` instead

2024-09-11 15:50 UTC, flo-dup commented on dynawo-integration-tests/src/test/java/com/powsybl/dynawo/it/DynawoSimulationTest.java
> +        dynawoSimulationParameters.setCriteriaFilePath(Path.of(Objects.requireNonNull(getClass().getResource("/ieee14/criteria.crt")).getPath()));
I tested with a wrong xml file and the test passes... Is there any way to see that the file was correctly taken into account @gautierbureau ?

2024-09-30 07:35 UTC, gautierbureau commented on dynawo-integration-tests/src/test/java/com/powsybl/dynawo/it/DynawoSimulationTest.java
> +        dynawoSimulationParameters.setCriteriaFilePath(Path.of(Objects.requireNonNull(getClass().getResource("/ieee14/criteria.crt")).getPath()));
What was in the file ? maybe the xsd int not checked I don't remember. As this file is optional I don't know what checks we do...

2024-10-07 11:30 UTC, flo-dup approved these changes

2024-10-07 11:31 UTC, merged