Refactor Dynawo constants
powsybl/powsybl-dynawo pull request #395
Opened 2024-10-11 12:51 UTC by Lisrte

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Refactor

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**
Merge the 2 `DynawoSimulationConstants` classes
Remove constants duplicate
Move `DynawoSimulationParameters.ExportMode` to commons

**Does this PR introduce a breaking change or deprecate an API?**
- [x] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [x] The *Breaking Change* or *Deprecated* label has been added
- [x] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

Replace `com.powsybl.dynawo.DynawoSimulationParameters.ExportMode` with 
`com.powsybl.dynawo.commons.ExportMod`

**Other information**:

2024-11-06 14:30 UTC, flo-dup requested changes

2024-11-06 14:30 UTC, flo-dup commented on commons/src/main/java/com/powsybl/dynawo/commons/DynawoConstants.java
> +    public static final String FINAL_STATE_FOLDER = "finalState";
Isn't this always used with `OUTPUTS_FOLDER`? then we could put it in a `Path` together with it.

2024-11-08 10:09 UTC, Lisrte commented on commons/src/main/java/com/powsybl/dynawo/commons/DynawoConstants.java
> +    public static final String OUTPUT_IIDM_FILENAME_FULL_PATH = "%s/%s/%s".formatted(OUTPUTS_FOLDER, FINAL_STATE_FOLDER, OUTPUT_IIDM_FILENAME);
A `Path` can't be resolved directly against another `Path` instantiated with a different `FileSystem` thus I will keep the `String` with a `File.separator` replacing the `/`

2024-11-08 16:46 UTC, flo-dup approved these changes

2024-11-08 16:51 UTC, merged