Add IEEE57 disconnect generator unit test
powsybl/powsybl-dynawo pull request #46
Opened 2020-09-14 13:00 UTC by marcosmc

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the new behavior (if this is a feature change)?**
Include the IEEE57 Disconnect Generator unit test, without events, in the powsybl dynawo project.

2020-09-14 15:16 UTC, agnesLeroy reviewed
@marcosmc I don't understand this PR: it seems there are the same files as in the other one that's currently open. Is it a mistake?

2020-09-14 16:08 UTC, mathbagu commented
> @marcosmc I don't understand this PR: it seems there are the same files as in the other one that's currently open. Is it a mistake?

I imagine he creates his new branch from the other one because it's not merged yet

2020-09-15 05:34 UTC, marcosmc commented
> @marcosmc I don't understand this PR: it seems there are the same files as in the other one that's currently open. Is it a mistake?

Sorry, as Mathieu comments, I started the branch from the other and I created the PR before merging the first one.

2020-10-05 16:53 UTC, mathbagu requested changes

2020-10-05 16:53 UTC, mathbagu commented on src/test/java/com/powsybl/dynawo/ieee/AbstractIeeeTest.java
> +        Files.copy(getClass().getResourceAsStream(parametersJson), fileSystem.getPath("/dynawoParameters.json"), StandardCopyOption.REPLACE_EXISTING);
From my point of view there is a design issue. You need to overwrite existing file, meaning that our unit-test are not fully independent. I think this is the case because you use the filesystem get from the configuration to store files. I really think this could lead to unexpected behavior.

If you cannot use another filesystem instance, maybe we should create a temporary directory and remove in the tear down method. Another option is to have common configuration files to all test cases... 

I don't really know for now what is the best solution.

2020-10-09 08:34 UTC, mathbagu approved these changes

2020-10-09 08:35 UTC, merged