Import the output curves (CSV) to a TimeSeries
powsybl/powsybl-dynawo pull request #48
Opened 2020-10-07 10:45 UTC by marcosmc

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the new behavior (if this is a feature change)?**
Import the output curves file to a TimeSeries and store in the DynamicSimulationResult class.

2020-10-22 14:55 UTC, zamarrenolm approved these changes

2020-10-28 11:06 UTC, mathbagu requested changes
I have mainly 3 remarks
- I think we should move the attributes of DynawoResult in the API
- I think we should try to move the parsing of the timeseries in the time-series-api. The existing code could be adapted to read CSV that doesn't contain the version column.
- You have to update all the test cases, adding the reference file and assert the result is the expected one.

2021-01-19 12:00 UTC, geofjamg commented
@marcosmc Now that we have merged related PRs in core, this one should be ok? Could you check it is still working?

2021-01-19 15:45 UTC, marcosmc commented
> @marcosmc Now that we have merged related PRs in core, this one should be ok? Could you check it is still working?

Done and fix it.

2021-01-19 19:52 UTC, geofjamg approved these changes

2021-01-19 19:52 UTC, merged