Dynaflow_Integration: Classes DynaflowParameters, DynaflowConfig and …
powsybl/powsybl-dynawo pull request #51
Opened 2020-10-09 12:44 UTC by PerninGuillaume

…their associated test classes, DynaflowConfig takes care of high level parameters and commands constructions, DynaflowParameters takes care of the specific parameters and write them to an output stream with the use of a Json serializer

Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
This PR introduce a beginning to the integration of Dynaflow-launcher to Powsybl-dynawo.

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-10-09 14:12 UTC, mathbagu requested changes

2020-10-09 14:12 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowParametersTest.java
> +        assertEquals(fileParams, generatedParams);
It's correct but we already have this kind of feature: Inherit from AbstractConverterTest and use `compareTxt`

2020-10-09 14:46 UTC, PerninGuillaume commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +    public static final boolean LCC_AS_LOADS = true;
Even the Module_specific_parameters ?

2020-10-09 14:51 UTC, PerninGuillaume commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +        jsonGenerator.writeObjectFieldStart("dfl-config");
De florent lorsque je lui ai dit la meme remarque : "l'objet dfl-config ets là pour s'assurer qu'on ne se trompe pas si jamais on veut intégrer ça dans un autre JSON, c'est une sorte de namespace."

2020-10-12 08:39 UTC, PerninGuillaume commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +    public void writeConfigInputFile(OutputStream outputStream, LoadFlowParameters params) throws IOException {
I need to access this method in DynaflowProvider though, If I put it as private how will I be able to use it ?

2020-10-12 10:59 UTC, mathbagu requested changes

2020-10-12 10:59 UTC, mathbagu commented on pom.xml
> +        <powsyblcore.version>3.6.0</powsyblcore.version>
This is not resolved yet

2020-10-12 10:59 UTC, mathbagu commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +        try (FileOutputStream outputStream = new FileOutputStream(workingDir.resolve(CONFIG_FILENAME).toString())) {
Use `Files.newOutputStream` instead:
```
try (FileOutputStream outputStream = Files.newOutputStream(workingDir.resolve(CONFIG_FILENAME)) {
    ....
}
```

2020-10-12 10:59 UTC, mathbagu commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +    public void writeConfigInputFile(OutputStream outputStream, LoadFlowParameters params) throws IOException {
If DynawoProvider and the utility class are in the same package, it's ok (see. https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html)

2020-10-12 10:59 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +    String homeDir = "homeDir";
male these parameters private and final

2020-10-12 10:59 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        homeDir = "homeDir";
Seems useless

2020-10-12 10:59 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        platformConfig = new InMemoryPlatformConfig(fileSystem);
Why platformConfig is not a local variable?

2020-10-12 10:59 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        Path pathHomeDir = Paths.get(homeDir);
Pay attention: Paths.get return a path from the default filesystem. You should use the in-memory filesystem instead.

2020-10-12 10:59 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        moduleConfig.setStringProperty("debug", Objects.toString(debug));
Use Boolean.toString or "true/false" litteral

2020-10-12 10:59 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowParametersTest.java
> +        LoadFlowParameters parameters = LoadFlowParameters.load(platformConfig);
Your two unit tests are not independant. If I run them in parallel this will lead to unexpected behavior. Either initialize the module in the setup or create local variables.

2020-10-12 11:24 UTC, PerninGuillaume commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        moduleConfig.setStringProperty("debug", Objects.toString(debug));
Objects.toString(...) is used intensively in testing in powsybl-rte-core like in ADNSensitivityComputationParametersTest, is Boolean.toString better ?

2020-10-12 11:31 UTC, PerninGuillaume commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        homeDir = "homeDir";
Do you mean the entire method setUp ? Should I create and close the fileSystem in the test ?

2020-10-12 11:35 UTC, PerninGuillaume commented on pom.xml
> +        <powsyblcore.version>3.6.0</powsyblcore.version>
Yes it was not, however now it should be

2020-10-12 12:01 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        moduleConfig.setStringProperty("debug", Objects.toString(debug));
Yes! internal project doesn't have the same quality requirements than this one.

2020-10-12 12:01 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowConfigTest.java
> +        homeDir = "homeDir";
Nop the `homeDir = "homeDir";` statement is redundant with the initialization at line 33. You should not modify this variable in the unit tests

2020-10-14 12:39 UTC, mathbagu commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +    void writeConfigInputFile(Path workingDir, LoadFlowParameters params) throws IOException {
Please, could you proceed with the refactoring I proposed last week?

2020-10-14 12:40 UTC, mathbagu commented on src/main/java/com/powsybl/dynaflow/DynaflowParameters.java
> +                    .ifPresent(config -> {
Sonar report an issue here: this lambda has a single instruction, so you should remove the brace

2020-10-14 12:42 UTC, mathbagu commented on src/test/java/com/powsybl/dynaflow/DynaflowParametersTest.java
> +        fileParams.close();
Use the try-with-resources pattern

2020-10-17 09:26 UTC, mathbagu approved these changes

2020-10-19 14:34 UTC, merged