Update network
powsybl/powsybl-dynawo pull request #74
Opened 2021-03-16 15:08 UTC by guillemjane-AIA

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Introduces a feature which will be used to update a network with results coming from Dynawo.
This feature will be used in DynaFlow and DynaWaltz integration.

2021-03-16 15:21 UTC, zamarrenolm approved these changes

2021-03-16 15:36 UTC, mathbagu requested changes

2021-03-16 15:36 UTC, mathbagu commented on commons/pom.xml
> +    </build>
To be check

2021-03-16 15:36 UTC, mathbagu commented on commons/pom.xml
> +            <groupId>${project.groupId}</groupId>
Could you please use `com.powsybl` for powsybl-core dependencies. The idea is to consider powsybl-core as an external project.

Same remark for all powsybl-core dependencies declared in this pom.xml file

2021-03-16 15:36 UTC, mathbagu commented on commons/src/main/java/DynawoResultsNetworkUpdate.java
> +import com.powsybl.iidm.network.*;
Don't forget to add the license. @guillemjane-AIA could you please configure your IDE to avoid forgetting to insert the header when you create a new file.

2021-03-16 15:36 UTC, mathbagu commented on commons/src/main/java/DynawoResultsNetworkUpdate.java
> +        }
From my point of view, you should call connect / disconnect directly without checking even if the status are the same. To be check, but I think if the terminal is connected, it does nothing (same if it's already disconnected).

2021-03-16 15:36 UTC, mathbagu commented on commons/src/test/java/DynawoResultsNetworkUpdateTest.java
> +import com.powsybl.commons.AbstractConverterTest;
Add the license header

2021-03-16 15:36 UTC, mathbagu commented on commons/src/test/java/DynawoResultsNetworkUpdateTest.java
> +    public void testUpdate()  throws IOException {
Coding style: remove the extra space between `()` and `throws`. Could you confirm an `IOException` can be thrown by this code?

2021-03-16 15:36 UTC, mathbagu commented on pom.xml
> +                <groupId>${project.groupId}</groupId>
Could you please consider powsybl-core dependencies in the whole file.

2021-03-16 15:36 UTC, mathbagu commented on commons/src/main/java/DynawoResultsNetworkUpdate.java
> +        }
You should also consider ThreeWindingsTransformers or at least throw an exception because this connectable is not supported yet by Dynawo

2021-03-16 15:36 UTC, mathbagu commented on commons/src/main/java/DynawoResultsNetworkUpdate.java
> +        }
About buses, are you sure this is working well if the network is described in Node/Breaker topology, then exported in Bus/Breaker view and then map back to the original network? Maybe you should add a unit test with that use case

2021-03-16 18:26 UTC, zamarrenolm commented on commons/src/main/java/DynawoResultsNetworkUpdate.java
> +        }
We will add a unit test for that specific scenario, but it should work as it is: the set of V, angle in the bus view will propagate its values to the Bus/Breaker configured buses.

In addition, we are updating Dynawo to support Node/Breaker networks, so in the future the network passed to Dynawo   will be written at the same topology level it was defined.

2021-03-17 18:28 UTC, guillemjane-AIA commented on commons/src/test/java/DynawoResultsNetworkUpdateTest.java
> +    public void testUpdate()  throws IOException {
on the new test functions IOExceptions are coming from compare.

2021-03-24 10:43 UTC, zamarrenolm approved these changes

2021-03-24 10:45 UTC, zamarrenolm commented on pom.xml
> +                <groupId>${project.groupId}</groupId>
done; now using `com.powsybl` instead of `${project.groupId}` for powsybl-core modules.

2021-03-24 10:50 UTC, merged