Test update iidm dynaflow
powsybl/powsybl-dynawo pull request #77
Opened 2021-04-06 18:29 UTC by guillemjane-AIA

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature

**What is the current behavior?** *(You can also link to an open issue here)*
Updating results from dynaflow-launcher not present

**What is the new behavior (if this is a feature change)?**
Added Update network with results coming from dynaflow-launcher.

2021-04-08 10:09 UTC, gautierbureau requested changes

2021-04-08 10:09 UTC, gautierbureau commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowProvider.java
> +                DynawoResultsNetworkUpdate.update(network, NetworkXml.read(workingDir.resolve("outputs").resolve("finalState").resolve("outputIIDM.xml")));
why not using OUTPUT_IIDM_FILENAME ?

2021-04-09 14:14 UTC, zamarrenolm commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowProvider.java
> +                DynawoResultsNetworkUpdate.update(network, NetworkXml.read(workingDir.resolve("outputs").resolve("finalState").resolve("outputIIDM.xml")));
totally right, we should use the defined constant; we made the change

2021-04-12 08:25 UTC, gautierbureau approved these changes

2021-04-12 09:57 UTC, zamarrenolm approved these changes

2021-04-12 11:27 UTC, mathbagu requested changes

2021-04-12 11:27 UTC, mathbagu commented on dynaflow/pom.xml
> +            <groupId>com.powsybl</groupId>
Should be `${project.groupId}` as powsybl-dynawo-commons is part of this repository

2021-04-12 11:27 UTC, mathbagu commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowProvider.java
> + * Copyright (c) 2021, RTE (http://www.rte-france.com)
The copyright date should be unchanged: this year defines the beginning of the copyright

2021-04-12 11:27 UTC, mathbagu commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> + * Copyright (c) 2021, RTE (http://www.rte-france.com)
Same remark here

2021-04-12 11:27 UTC, mathbagu commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +public class DynaFlowProviderTest extends AbstractConverterTest {
As we inherit from `AbstractConverterTest`, this class should be cleaned up: the base class provides a filesystem you should use instead of creating a new one to avoid misunderstanding behaviour

2021-04-12 11:27 UTC, mathbagu commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +        public LocalCommandExecutorMock(String stdoutFileRef, String outPutIIDM) {
I think we should write `outputIidm` to follow the coding style.

2021-04-12 11:38 UTC, zamarrenolm commented on dynaflow/pom.xml
> +            <groupId>com.powsybl</groupId>
fixed

2021-04-12 11:38 UTC, zamarrenolm commented on dynaflow/src/main/java/com/powsybl/dynaflow/DynaFlowProvider.java
> + * Copyright (c) 2021, RTE (http://www.rte-france.com)
fixed

2021-04-12 11:38 UTC, zamarrenolm commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> + * Copyright (c) 2021, RTE (http://www.rte-france.com)
fixed

2021-04-12 11:38 UTC, zamarrenolm commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +public class DynaFlowProviderTest extends AbstractConverterTest {
removed local filesystem instance

2021-04-12 11:39 UTC, zamarrenolm commented on dynaflow/src/test/java/com/powsybl/dynaflow/DynaFlowProviderTest.java
> +        public LocalCommandExecutorMock(String stdoutFileRef, String outPutIIDM) {
fixed following case convention

2021-04-12 11:43 UTC, mathbagu approved these changes

2021-04-12 12:42 UTC, merged